version: '3'

volumes:
  db_data:

services:
  db:
    image: salesfelipedev/lang-db:latest
    ports:
      - "3306:3306"
    volumes: 
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - languages_net
  app:
    image: salesfelipedev/lang-app:latest
    ports:
      - "8080:8080"
    networks:
      - languages_net
networks:
  languages_net: {}